import type { Metadata } from "next";
import { Delius as FontSans } from "next/font/google";
import "./globals.css";

const font = FontSans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Will You Be My Valentine?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
