export const requestArr = [
  "No",
  "Really Not?",
  "Think Again",
  "Last Chance!",
  "Surely Not!",
  "You might Regret this!",
  "Give another thought!",
  "Why you deny such a charming request?",
  "I promise it'll be worth it!",
  "You're missing out on something special!",
  "Life's too short to say no!",
  "I'll make it worth your while!",
  "Indulge in a little spontaneity!",
  "You won't regret saying yes!",
  "Just say yes and see what happens!",
  "You're too irresistible to say no to!",
  "I've got a good feeling about this!",
  "Join me for an adventure!",
  "You're too tempting to resist!",
  "Saying yes never felt so right!",
  "Take a chance, say yes!",
  "Let's create some magic together!",
  "I'll make sure you won't regret it!",
  "You'll thank yourself for saying yes!",
  "Trust me, it'll be amazing!",
  "Don't let this opportunity slip away!",
  "Let's turn this moment into something special!",
  "Life's an adventure, let's embrace it!",
  "Let's make a memory you'll never forget!",
  "You won't regret giving in to temptation!",
  "Just say yes and let's make it happen!",
  "You won't want to miss out on this!",
  "I'll make it worth your while, I promise!",
  "You're too charming to resist!",
  "Take my hand and let's do this together!",
  "Let's create some sparks!",
  "Let's make a story worth telling!",
  "Say yes and let's make magic happen!",
  "Why resist such a tempting offer?",
];

export const violenceKeywords = [
  "hello",
  "bhoot",
  "gay",
  "blah",
  "lewda",
  "lund",
  "chup",
  "nahi",
  "madarchod",
  "bauba chauba",
  "nigga",
  "baap",
  "hitler",
  "nigachu",
  "fuck",
  "xyz",
  "ghansyam bhai ghoge wala",
  "subham",
  "richik",
  "hameed",
  "siiiiiiiiiiiiiiiiiiii",
  "pranjal",
  "xxxxxxxxxx",
  "hii",
  "sanskruti",
  "aaaaa",
  "bokachoda",
  "abc",
  "shivam",
  "akash",
  "gghhh",
  "ggg",
  "ghvxsd",
  "not so fast",
  "fefe",
  "huu",
  "rabi",
  "mukul",
  "jsjsjse",
  "tikku",
  "papa",
  "zareen",
  "daddy",
  "lang",
  "ghg",
  "xxx",
  "sum",
  "vinod",
  "kash",
  "vini",
  "pepe",
  "ginni",
  "saidarshan",
  "ajay",
  "divya",
  "rushabh",
  "hgfhh",
  "rishang",
  "suman",
  "ghhb",
  "cvhh",
  "bdh",
  "bitch",
  "your baby",
  "jyotiswaroop srivastava",
  "garv",
  "jodd",
  "007",
  "ghh",
  "jay",
  "sam",
  "rahul",
  "chhu",
  "tuhin",
  "ari",
  "punk",
  "chut",
  "naval",
  "lucifer",
  "arup",
];
